main: dev.cibmc.spigot.blankplugin.App
name: BlankPlugin
version: 0.1
api-version: 1.18
depend: 
  - PlaceholderAPI
  - Vault
  - SmartInvs
commands:
   wild:
      description: Teleports you to a random location.
      usage: /<command>
   randomteleport:
      description: Displays information about the plugin
      usage: /<command>
   diamond:
      description: Makes A Diamond Appear In Front Of YOu
      usage: /<command>
   setgenerator:
      description: Creates A Generator
      usage: /<command> <block>
   blank:
      description: Reloads The Plugin
      usage: /<command>
   giveitems:
      description: Gives Debug Items
      usage: /<command>
   givedroppers:
      description: Gives Debug Droppers
      usage: /<command>
   sell:
      description: Tests Money Maker
      usage: /<command>